-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_tpg_0_0_tpgBackground is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    height : IN STD_LOGIC_VECTOR (15 downto 0);
    width : IN STD_LOGIC_VECTOR (15 downto 0);
    bckgndId : IN STD_LOGIC_VECTOR (7 downto 0);
    ZplateHorContStart : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateHorContDelta : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContStart : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContDelta : IN STD_LOGIC_VECTOR (15 downto 0);
    dpDynamicRange : IN STD_LOGIC_VECTOR (7 downto 0);
    dpYUVCoef : IN STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed : IN STD_LOGIC_VECTOR (7 downto 0);
    colorFormat : IN STD_LOGIC_VECTOR (7 downto 0);
    ovrlayYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_full_n : IN STD_LOGIC;
    ovrlayYUV_write : OUT STD_LOGIC;
    s : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of design_1_v_tpg_0_0_tpgBackground is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_4C : STD_LOGIC_VECTOR (7 downto 0) := "01001100";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_95 : STD_LOGIC_VECTOR (7 downto 0) := "10010101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv8_6B : STD_LOGIC_VECTOR (7 downto 0) := "01101011";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv14_7 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000111";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal rampStart : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal rampVal_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rampVal : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal xBar_V : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal zonePlateVDelta : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal hdata : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rampVal_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal trunc_ln506_fu_626_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal cmp2_i322_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp6_i_fu_650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampStart_load_reg_1217 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln260_fu_782_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln260_reg_1223 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln_fu_790_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_reg_1228 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_1_reg_1238 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal cmp12_i_fu_870_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp12_i_reg_1246 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln518_fu_859_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1488_fu_887_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1488_reg_1251 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln1592_fu_905_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_reg_1256 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_1_fu_918_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_1_reg_1261 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_2_fu_925_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1592_2_reg_1266 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_start : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_done : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_idle : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_ready : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ovrlayYUV_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ovrlayYUV_write : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i390 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i373 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i356 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i337_cast_cast : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i_cast : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i10_i354_cast_cast_cast_cast : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i10_i335 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i10_i329 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_select_ln1099_1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_cmp57_i : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_barWidth_cast : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_barWidth : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_trunc_ln : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_cmp85_i : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hBarSel_4_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hBarSel_4_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_lhs_out_o : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_lhs_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVAddr_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVAddr_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVDelta_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVDelta_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_2_0_0_0492_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_2_0_0_0492_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_1_0_0_0490_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_1_0_0_0490_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_0_0_0_0488_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_0_0_0_0488_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hBarSel_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hBarSel_2_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_xBar_V : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_xBar_V_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVAddr_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVDelta : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVDelta_ap_vld : STD_LOGIC;
    signal ap_phi_mux_rampVal_3_flag_0_phi_fu_392_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_3_flag_0_reg_388 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_phi_mux_hdata_flag_0_phi_fu_404_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal hdata_flag_0_reg_400 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rampVal_2_flag_0_phi_fu_416_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_2_flag_0_reg_412 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal rampVal_3_new_0_fu_306 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_3_loc_0_fu_302 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_loc_0_fu_298 : STD_LOGIC_VECTOR (15 downto 0);
    signal hBarSel_4_loc_0_fu_294 : STD_LOGIC_VECTOR (7 downto 0);
    signal xBar_V_loc_0_fu_290 : STD_LOGIC_VECTOR (10 downto 0);
    signal zonePlateVAddr_loc_0_fu_286 : STD_LOGIC_VECTOR (15 downto 0);
    signal zonePlateVDelta_loc_0_fu_282 : STD_LOGIC_VECTOR (15 downto 0);
    signal hdata_new_0_fu_278 : STD_LOGIC_VECTOR (15 downto 0);
    signal hdata_loc_0_fu_274 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_2_new_0_fu_270 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_2_loc_0_fu_266 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_0_2_0_0_0493_lcssa502_fu_262 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_1_0_0_0491_lcssa499_fu_258 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0489_lcssa496_fu_254 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln705_fu_937_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_fu_250 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_2_fu_864_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1212_fu_754_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_i_fu_704_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_726_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln518_fu_855_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal Sel_fu_877_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln1592_fu_893_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1592_1_fu_899_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1592_2_fu_912_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ovrlayYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        ovrlayYUV_full_n : IN STD_LOGIC;
        ovrlayYUV_write : OUT STD_LOGIC;
        rampVal_3_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
        conv2_i_i_i390 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i_i373 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i_i356 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i_i337_cast_cast : IN STD_LOGIC_VECTOR (4 downto 0);
        conv2_i_i_i_cast : IN STD_LOGIC_VECTOR (0 downto 0);
        select_ln260 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i10_i354_cast_cast_cast_cast : IN STD_LOGIC_VECTOR (2 downto 0);
        conv2_i_i10_i335 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i10_i329 : IN STD_LOGIC_VECTOR (7 downto 0);
        rampStart_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        Zplate_Hor_Control_Start : IN STD_LOGIC_VECTOR (15 downto 0);
        bckgndId_load : IN STD_LOGIC_VECTOR (7 downto 0);
        cmp2_i322 : IN STD_LOGIC_VECTOR (0 downto 0);
        zext_ln1032 : IN STD_LOGIC_VECTOR (7 downto 0);
        y : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp6_i : IN STD_LOGIC_VECTOR (0 downto 0);
        select_ln1099_1 : IN STD_LOGIC_VECTOR (1 downto 0);
        cmp57_i : IN STD_LOGIC_VECTOR (0 downto 0);
        barWidth_cast : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidth : IN STD_LOGIC_VECTOR (10 downto 0);
        shl_ln : IN STD_LOGIC_VECTOR (15 downto 0);
        Zplate_Ver_Control_Start : IN STD_LOGIC_VECTOR (15 downto 0);
        Zplate_Hor_Control_Delta : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp12_i : IN STD_LOGIC_VECTOR (0 downto 0);
        Zplate_Ver_Control_Delta : IN STD_LOGIC_VECTOR (15 downto 0);
        trunc_ln7 : IN STD_LOGIC_VECTOR (13 downto 0);
        trunc_ln : IN STD_LOGIC_VECTOR (13 downto 0);
        colorFormatLocal : IN STD_LOGIC_VECTOR (7 downto 0);
        loopHeight : IN STD_LOGIC_VECTOR (15 downto 0);
        add_ln1488 : IN STD_LOGIC_VECTOR (7 downto 0);
        cmp85_i : IN STD_LOGIC_VECTOR (0 downto 0);
        or_ln1592 : IN STD_LOGIC_VECTOR (0 downto 0);
        or_ln1592_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        or_ln1592_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        dpDynamicRange_load : IN STD_LOGIC_VECTOR (7 downto 0);
        dpYUVCoef_load : IN STD_LOGIC_VECTOR (7 downto 0);
        rampVal_3_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_3_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_4_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        lhs_out_i : IN STD_LOGIC_VECTOR (10 downto 0);
        lhs_out_o : OUT STD_LOGIC_VECTOR (10 downto 0);
        lhs_out_o_ap_vld : OUT STD_LOGIC;
        zonePlateVAddr_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        zonePlateVDelta_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVDelta_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVDelta_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hdata_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_1_out_ap_vld : OUT STD_LOGIC;
        hdata_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_new_1_out_ap_vld : OUT STD_LOGIC;
        hdata_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_2_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_0492_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_2_0_0_0492_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_2_0_0_0492_out_o_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_0490_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0490_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0490_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0488_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0488_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0488_out_o_ap_vld : OUT STD_LOGIC;
        rampVal : OUT STD_LOGIC_VECTOR (7 downto 0);
        rampVal_ap_vld : OUT STD_LOGIC;
        hBarSel_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_2_ap_vld : OUT STD_LOGIC;
        xBar_V : OUT STD_LOGIC_VECTOR (10 downto 0);
        xBar_V_ap_vld : OUT STD_LOGIC;
        s : IN STD_LOGIC_VECTOR (31 downto 0);
        zonePlateVAddr : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_ap_vld : OUT STD_LOGIC;
        zonePlateVDelta : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVDelta_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424 : component design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_start,
        ap_done => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_done,
        ap_idle => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_idle,
        ap_ready => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_ready,
        ovrlayYUV_din => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ovrlayYUV_din,
        ovrlayYUV_num_data_valid => ap_const_lv5_0,
        ovrlayYUV_fifo_cap => ap_const_lv5_0,
        ovrlayYUV_full_n => ovrlayYUV_full_n,
        ovrlayYUV_write => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ovrlayYUV_write,
        rampVal_3_flag_0 => rampVal_3_flag_0_reg_388,
        hdata_flag_0 => hdata_flag_0_reg_400,
        rampVal_2_flag_0 => rampVal_2_flag_0_reg_412,
        loopWidth => width,
        conv2_i_i_i390 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i390,
        conv2_i_i_i373 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i373,
        conv2_i_i_i356 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i356,
        conv2_i_i_i337_cast_cast => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i337_cast_cast,
        conv2_i_i_i_cast => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i_cast,
        select_ln260 => select_ln260_reg_1223,
        conv2_i_i10_i354_cast_cast_cast_cast => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i10_i354_cast_cast_cast_cast,
        conv2_i_i10_i335 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i10_i335,
        conv2_i_i10_i329 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i10_i329,
        rampStart_1 => rampStart_load_reg_1217,
        Zplate_Hor_Control_Start => ZplateHorContStart,
        bckgndId_load => bckgndId,
        cmp2_i322 => cmp2_i322_fu_630_p2,
        zext_ln1032 => rampStart_load_reg_1217,
        y => y_1_reg_1238,
        cmp6_i => cmp6_i_fu_650_p2,
        select_ln1099_1 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_select_ln1099_1,
        cmp57_i => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_cmp57_i,
        barWidth_cast => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_barWidth_cast,
        barWidth => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_barWidth,
        shl_ln => shl_ln_reg_1228,
        Zplate_Ver_Control_Start => ZplateVerContStart,
        Zplate_Hor_Control_Delta => ZplateHorContDelta,
        cmp12_i => cmp12_i_reg_1246,
        Zplate_Ver_Control_Delta => ZplateVerContDelta,
        trunc_ln7 => trunc_ln506_fu_626_p1,
        trunc_ln => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_trunc_ln,
        colorFormatLocal => colorFormat,
        loopHeight => height,
        add_ln1488 => add_ln1488_reg_1251,
        cmp85_i => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_cmp85_i,
        or_ln1592 => or_ln1592_reg_1256,
        or_ln1592_1 => or_ln1592_1_reg_1261,
        or_ln1592_2 => or_ln1592_2_reg_1266,
        dpDynamicRange_load => dpDynamicRange,
        dpYUVCoef_load => dpYUVCoef,
        rampVal_3_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_flag_1_out,
        rampVal_3_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_flag_1_out_ap_vld,
        rampVal_3_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_new_1_out,
        rampVal_3_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_new_1_out_ap_vld,
        rampVal_3_loc_1_out_i => rampVal_3_loc_0_fu_302,
        rampVal_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_loc_1_out_o,
        rampVal_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_loc_1_out_o_ap_vld,
        rampVal_loc_1_out_i => rampVal_loc_0_fu_298,
        rampVal_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_loc_1_out_o,
        rampVal_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_loc_1_out_o_ap_vld,
        hBarSel_4_loc_1_out_i => hBarSel_4_loc_0_fu_294,
        hBarSel_4_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hBarSel_4_loc_1_out_o,
        hBarSel_4_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hBarSel_4_loc_1_out_o_ap_vld,
        lhs_out_i => xBar_V_loc_0_fu_290,
        lhs_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_lhs_out_o,
        lhs_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_lhs_out_o_ap_vld,
        zonePlateVAddr_loc_1_out_i => zonePlateVAddr_loc_0_fu_286,
        zonePlateVAddr_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVAddr_loc_1_out_o,
        zonePlateVAddr_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVAddr_loc_1_out_o_ap_vld,
        zonePlateVDelta_loc_1_out_i => zonePlateVDelta_loc_0_fu_282,
        zonePlateVDelta_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVDelta_loc_1_out_o,
        zonePlateVDelta_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVDelta_loc_1_out_o_ap_vld,
        hdata_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_flag_1_out,
        hdata_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_flag_1_out_ap_vld,
        hdata_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_new_1_out,
        hdata_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_new_1_out_ap_vld,
        hdata_loc_1_out_i => hdata_loc_0_fu_274,
        hdata_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_loc_1_out_o,
        hdata_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_loc_1_out_o_ap_vld,
        rampVal_2_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_flag_1_out,
        rampVal_2_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_flag_1_out_ap_vld,
        rampVal_2_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_new_1_out,
        rampVal_2_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_new_1_out_ap_vld,
        rampVal_2_loc_1_out_i => rampVal_2_loc_0_fu_266,
        rampVal_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_loc_1_out_o,
        rampVal_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_loc_1_out_o_ap_vld,
        p_0_2_0_0_0492_out_i => p_0_2_0_0_0493_lcssa502_fu_262,
        p_0_2_0_0_0492_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_2_0_0_0492_out_o,
        p_0_2_0_0_0492_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_2_0_0_0492_out_o_ap_vld,
        p_0_1_0_0_0490_out_i => p_0_1_0_0_0491_lcssa499_fu_258,
        p_0_1_0_0_0490_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_1_0_0_0490_out_o,
        p_0_1_0_0_0490_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_1_0_0_0490_out_o_ap_vld,
        p_0_0_0_0_0488_out_i => p_0_0_0_0_0489_lcssa496_fu_254,
        p_0_0_0_0_0488_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_0_0_0_0488_out_o,
        p_0_0_0_0_0488_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_0_0_0_0488_out_o_ap_vld,
        rampVal => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal,
        rampVal_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_ap_vld,
        hBarSel_2 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hBarSel_2,
        hBarSel_2_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hBarSel_2_ap_vld,
        xBar_V => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_xBar_V,
        xBar_V_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_xBar_V_ap_vld,
        s => s,
        zonePlateVAddr => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVAddr,
        zonePlateVAddr_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVAddr_ap_vld,
        zonePlateVDelta => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVDelta,
        zonePlateVDelta_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVDelta_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_859_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_859_p2 = ap_const_lv1_0))) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_ready = ap_const_logic_1)) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    hBarSel_4_loc_0_fu_294_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_4_loc_0_fu_294 <= hBarSel_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hBarSel_4_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                hBarSel_4_loc_0_fu_294 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hBarSel_4_loc_1_out_o;
            end if; 
        end if;
    end process;

    hdata_flag_0_reg_400_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                hdata_flag_0_reg_400 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_flag_1_out;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hdata_flag_0_reg_400 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    hdata_loc_0_fu_274_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hdata_loc_0_fu_274 <= hdata;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                hdata_loc_0_fu_274 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_2_flag_0_reg_412_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                rampVal_2_flag_0_reg_412 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_flag_1_out;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_2_flag_0_reg_412 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_2_loc_0_fu_266_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_2_loc_0_fu_266 <= rampVal_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                rampVal_2_loc_0_fu_266 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_3_flag_0_reg_388_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                rampVal_3_flag_0_reg_388 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_flag_1_out;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_3_flag_0_reg_388 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_3_loc_0_fu_302_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_3_loc_0_fu_302 <= rampVal_1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                rampVal_3_loc_0_fu_302 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_loc_0_fu_298_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_loc_0_fu_298 <= zext_ln1212_fu_754_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                rampVal_loc_0_fu_298 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_loc_1_out_o;
            end if; 
        end if;
    end process;

    xBar_V_loc_0_fu_290_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                xBar_V_loc_0_fu_290 <= xBar_V;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_lhs_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                xBar_V_loc_0_fu_290 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_lhs_out_o;
            end if; 
        end if;
    end process;

    y_fu_250_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_250 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_859_p2 = ap_const_lv1_0))) then 
                y_fu_250 <= y_2_fu_864_p2;
            end if; 
        end if;
    end process;

    zonePlateVAddr_loc_0_fu_286_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                zonePlateVAddr_loc_0_fu_286 <= zonePlateVAddr;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVAddr_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                zonePlateVAddr_loc_0_fu_286 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVAddr_loc_1_out_o;
            end if; 
        end if;
    end process;

    zonePlateVDelta_loc_0_fu_282_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                zonePlateVDelta_loc_0_fu_282 <= zonePlateVDelta;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVDelta_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                zonePlateVDelta_loc_0_fu_282 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVDelta_loc_1_out_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_859_p2 = ap_const_lv1_0))) then
                add_ln1488_reg_1251 <= add_ln1488_fu_887_p2;
                cmp12_i_reg_1246 <= cmp12_i_fu_870_p2;
                or_ln1592_1_reg_1261 <= or_ln1592_1_fu_918_p2;
                or_ln1592_2_reg_1266 <= or_ln1592_2_fu_925_p2;
                or_ln1592_reg_1256 <= or_ln1592_fu_905_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hBarSel_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                hBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hBarSel_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_hdata_flag_0_phi_fu_404_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_859_p2 = ap_const_lv1_1))) then
                hdata <= hdata_new_0_fu_278;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                hdata_new_0_fu_278 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_hdata_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_0_0_0_0488_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                p_0_0_0_0_0489_lcssa496_fu_254 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_0_0_0_0488_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_1_0_0_0490_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                p_0_1_0_0_0491_lcssa499_fu_258 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_1_0_0_0490_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_2_0_0_0492_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                p_0_2_0_0_0493_lcssa502_fu_262 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_p_0_2_0_0_0492_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_859_p2 = ap_const_lv1_1))) then
                rampStart <= add_ln705_fu_937_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                rampStart_load_reg_1217 <= rampStart;
                select_ln260_reg_1223 <= select_ln260_fu_782_p3;
                    shl_ln_reg_1228(15 downto 8) <= shl_ln_fu_790_p3(15 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_rampVal_3_flag_0_phi_fu_392_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_859_p2 = ap_const_lv1_1))) then
                rampVal_1 <= rampVal_3_new_0_fu_306;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_rampVal_2_flag_0_phi_fu_416_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_859_p2 = ap_const_lv1_1))) then
                rampVal_2 <= rampVal_2_new_0_fu_270;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                rampVal_2_new_0_fu_270 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_2_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                rampVal_3_new_0_fu_306 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_rampVal_3_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_xBar_V_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                xBar_V <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_xBar_V;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                y_1_reg_1238 <= y_fu_250;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVAddr_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVAddr;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVDelta_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                zonePlateVDelta <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_zonePlateVDelta;
            end if;
        end if;
    end process;
    shl_ln_reg_1228(7 downto 0) <= "00000000";

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln518_fu_859_p2, grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_859_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    Sel_fu_877_p4 <= y_fu_250(7 downto 6);
    add_i_fu_704_p2 <= std_logic_vector(unsigned(trunc_ln506_fu_626_p1) + unsigned(ap_const_lv14_7));
    add_ln1488_fu_887_p2 <= std_logic_vector(unsigned(rampStart) + unsigned(trunc_ln518_fu_855_p1));
    add_ln705_fu_937_p2 <= std_logic_vector(unsigned(motionSpeed) + unsigned(rampStart));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_done)
    begin
        if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln518_fu_859_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_859_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_mux_hdata_flag_0_phi_fu_404_p4 <= hdata_flag_0_reg_400;
    ap_phi_mux_rampVal_2_flag_0_phi_fu_416_p4 <= rampVal_2_flag_0_reg_412;
    ap_phi_mux_rampVal_3_flag_0_phi_fu_392_p4 <= rampVal_3_flag_0_reg_388;
    ap_ready <= internal_ap_ready;
    cmp12_i_fu_870_p2 <= "0" when (y_fu_250 = ap_const_lv16_0) else "1";
    cmp2_i322_fu_630_p2 <= "1" when (colorFormat = ap_const_lv8_0) else "0";
    cmp6_i_fu_650_p2 <= "1" when (colorFormat = ap_const_lv8_1) else "0";
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_start <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ap_start_reg;
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_barWidth <= add_i_fu_704_p2(13 downto 3);
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_barWidth_cast <= add_i_fu_704_p2(13 downto 3);
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_cmp57_i <= "0" when (colorFormat = ap_const_lv8_1) else "1";
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_cmp85_i <= "0" when (tmp_fu_726_p4 = ap_const_lv7_0) else "1";
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i10_i329 <= 
        ap_const_lv8_FF when (cmp2_i322_fu_630_p2(0) = '1') else 
        ap_const_lv8_4C;
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i10_i335 <= 
        ap_const_lv8_0 when (cmp2_i322_fu_630_p2(0) = '1') else 
        ap_const_lv8_95;
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i10_i354_cast_cast_cast_cast <= 
        ap_const_lv3_0 when (cmp2_i322_fu_630_p2(0) = '1') else 
        ap_const_lv3_5;
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i337_cast_cast <= 
        ap_const_lv5_0 when (cmp2_i322_fu_630_p2(0) = '1') else 
        ap_const_lv5_15;
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i356 <= 
        ap_const_lv8_FF when (cmp2_i322_fu_630_p2(0) = '1') else 
        ap_const_lv8_6B;
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i373 <= 
        ap_const_lv8_0 when (cmp2_i322_fu_630_p2(0) = '1') else 
        ap_const_lv8_80;
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i390 <= 
        ap_const_lv8_FF when (cmp2_i322_fu_630_p2(0) = '1') else 
        ap_const_lv8_80;
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_conv2_i_i_i_cast <= (cmp2_i322_fu_630_p2 xor ap_const_lv1_1);
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_select_ln1099_1 <= 
        ap_const_lv2_1 when (cmp6_i_fu_650_p2(0) = '1') else 
        ap_const_lv2_2;
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_trunc_ln <= height(14 - 1 downto 0);
    icmp_ln1592_1_fu_899_p2 <= "1" when (Sel_fu_877_p4 = ap_const_lv2_2) else "0";
    icmp_ln1592_2_fu_912_p2 <= "1" when (Sel_fu_877_p4 = ap_const_lv2_0) else "0";
    icmp_ln1592_fu_893_p2 <= "1" when (Sel_fu_877_p4 = ap_const_lv2_1) else "0";
    icmp_ln518_fu_859_p2 <= "1" when (y_fu_250 = height) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln518_fu_859_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_859_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    or_ln1592_1_fu_918_p2 <= (icmp_ln1592_2_fu_912_p2 or icmp_ln1592_1_fu_899_p2);
    or_ln1592_2_fu_925_p2 <= (icmp_ln1592_fu_893_p2 or icmp_ln1592_2_fu_912_p2);
    or_ln1592_fu_905_p2 <= (icmp_ln1592_fu_893_p2 or icmp_ln1592_1_fu_899_p2);
    ovrlayYUV_din <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ovrlayYUV_din;

    ovrlayYUV_write_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ovrlayYUV_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ovrlayYUV_write <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_424_ovrlayYUV_write;
        else 
            ovrlayYUV_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln260_fu_782_p3 <= 
        rampStart when (cmp2_i322_fu_630_p2(0) = '1') else 
        ap_const_lv8_80;
    shl_ln_fu_790_p3 <= (rampStart & ap_const_lv8_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_726_p4 <= colorFormat(7 downto 1);
    trunc_ln506_fu_626_p1 <= width(14 - 1 downto 0);
    trunc_ln518_fu_855_p1 <= y_fu_250(8 - 1 downto 0);
    y_2_fu_864_p2 <= std_logic_vector(unsigned(y_fu_250) + unsigned(ap_const_lv16_1));
    zext_ln1212_fu_754_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rampVal),16));
end behav;
