// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hud_accel_extract (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        this_buff_0_address0,
        this_buff_0_ce0,
        this_buff_0_q0,
        this_buff_0_address1,
        this_buff_0_ce1,
        this_buff_0_we1,
        this_buff_0_d1,
        this_buff_1_address0,
        this_buff_1_ce0,
        this_buff_1_q0,
        this_buff_1_address1,
        this_buff_1_ce1,
        this_buff_1_we1,
        this_buff_1_d1,
        this_buff_2_address0,
        this_buff_2_ce0,
        this_buff_2_q0,
        this_buff_2_address1,
        this_buff_2_ce1,
        this_buff_2_we1,
        this_buff_2_d1,
        this_buff_3_address0,
        this_buff_3_ce0,
        this_buff_3_q0,
        this_buff_3_address1,
        this_buff_3_ce1,
        this_buff_3_we1,
        this_buff_3_d1,
        this_buff_4_address0,
        this_buff_4_ce0,
        this_buff_4_q0,
        this_buff_4_address1,
        this_buff_4_ce1,
        this_buff_4_we1,
        this_buff_4_d1,
        this_buff_5_address0,
        this_buff_5_ce0,
        this_buff_5_q0,
        this_buff_5_address1,
        this_buff_5_ce1,
        this_buff_5_we1,
        this_buff_5_d1,
        this_buff_6_address0,
        this_buff_6_ce0,
        this_buff_6_q0,
        this_buff_6_address1,
        this_buff_6_ce1,
        this_buff_6_we1,
        this_buff_6_d1,
        this_buff_7_address0,
        this_buff_7_ce0,
        this_buff_7_q0,
        this_buff_7_address1,
        this_buff_7_ce1,
        this_buff_7_we1,
        this_buff_7_d1,
        p_read5,
        InImg_data156_dout,
        InImg_data156_num_data_valid,
        InImg_data156_fifo_cap,
        InImg_data156_empty_n,
        InImg_data156_read,
        p_read14,
        LEF_Img_data157_din,
        LEF_Img_data157_num_data_valid,
        LEF_Img_data157_fifo_cap,
        LEF_Img_data157_full_n,
        LEF_Img_data157_write,
        SEF_Img_data158_din,
        SEF_Img_data158_num_data_valid,
        SEF_Img_data158_fifo_cap,
        SEF_Img_data158_full_n,
        SEF_Img_data158_write
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] this_buff_0_address0;
output   this_buff_0_ce0;
input  [15:0] this_buff_0_q0;
output  [10:0] this_buff_0_address1;
output   this_buff_0_ce1;
output   this_buff_0_we1;
output  [15:0] this_buff_0_d1;
output  [10:0] this_buff_1_address0;
output   this_buff_1_ce0;
input  [15:0] this_buff_1_q0;
output  [10:0] this_buff_1_address1;
output   this_buff_1_ce1;
output   this_buff_1_we1;
output  [15:0] this_buff_1_d1;
output  [10:0] this_buff_2_address0;
output   this_buff_2_ce0;
input  [15:0] this_buff_2_q0;
output  [10:0] this_buff_2_address1;
output   this_buff_2_ce1;
output   this_buff_2_we1;
output  [15:0] this_buff_2_d1;
output  [10:0] this_buff_3_address0;
output   this_buff_3_ce0;
input  [15:0] this_buff_3_q0;
output  [10:0] this_buff_3_address1;
output   this_buff_3_ce1;
output   this_buff_3_we1;
output  [15:0] this_buff_3_d1;
output  [10:0] this_buff_4_address0;
output   this_buff_4_ce0;
input  [15:0] this_buff_4_q0;
output  [10:0] this_buff_4_address1;
output   this_buff_4_ce1;
output   this_buff_4_we1;
output  [15:0] this_buff_4_d1;
output  [10:0] this_buff_5_address0;
output   this_buff_5_ce0;
input  [15:0] this_buff_5_q0;
output  [10:0] this_buff_5_address1;
output   this_buff_5_ce1;
output   this_buff_5_we1;
output  [15:0] this_buff_5_d1;
output  [10:0] this_buff_6_address0;
output   this_buff_6_ce0;
input  [15:0] this_buff_6_q0;
output  [10:0] this_buff_6_address1;
output   this_buff_6_ce1;
output   this_buff_6_we1;
output  [15:0] this_buff_6_d1;
output  [10:0] this_buff_7_address0;
output   this_buff_7_ce0;
input  [15:0] this_buff_7_q0;
output  [10:0] this_buff_7_address1;
output   this_buff_7_ce1;
output   this_buff_7_we1;
output  [15:0] this_buff_7_d1;
input  [11:0] p_read5;
input  [15:0] InImg_data156_dout;
input  [2:0] InImg_data156_num_data_valid;
input  [2:0] InImg_data156_fifo_cap;
input   InImg_data156_empty_n;
output   InImg_data156_read;
input  [11:0] p_read14;
output  [15:0] LEF_Img_data157_din;
input  [2:0] LEF_Img_data157_num_data_valid;
input  [2:0] LEF_Img_data157_fifo_cap;
input   LEF_Img_data157_full_n;
output   LEF_Img_data157_write;
output  [15:0] SEF_Img_data158_din;
input  [2:0] SEF_Img_data158_num_data_valid;
input  [2:0] SEF_Img_data158_fifo_cap;
input   SEF_Img_data158_full_n;
output   SEF_Img_data158_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[10:0] this_buff_0_address0;
reg this_buff_0_ce0;
reg[10:0] this_buff_0_address1;
reg this_buff_0_ce1;
reg this_buff_0_we1;
reg[15:0] this_buff_0_d1;
reg[10:0] this_buff_1_address0;
reg this_buff_1_ce0;
reg[10:0] this_buff_1_address1;
reg this_buff_1_ce1;
reg this_buff_1_we1;
reg[15:0] this_buff_1_d1;
reg[10:0] this_buff_2_address0;
reg this_buff_2_ce0;
reg[10:0] this_buff_2_address1;
reg this_buff_2_ce1;
reg this_buff_2_we1;
reg[15:0] this_buff_2_d1;
reg[10:0] this_buff_3_address0;
reg this_buff_3_ce0;
reg[10:0] this_buff_3_address1;
reg this_buff_3_ce1;
reg this_buff_3_we1;
reg[15:0] this_buff_3_d1;
reg[10:0] this_buff_4_address0;
reg this_buff_4_ce0;
reg[10:0] this_buff_4_address1;
reg this_buff_4_ce1;
reg this_buff_4_we1;
reg[15:0] this_buff_4_d1;
reg[10:0] this_buff_5_address0;
reg this_buff_5_ce0;
reg[10:0] this_buff_5_address1;
reg this_buff_5_ce1;
reg this_buff_5_we1;
reg[15:0] this_buff_5_d1;
reg[10:0] this_buff_6_address0;
reg this_buff_6_ce0;
reg[10:0] this_buff_6_address1;
reg this_buff_6_ce1;
reg this_buff_6_we1;
reg[15:0] this_buff_6_d1;
reg[10:0] this_buff_7_address0;
reg this_buff_7_ce0;
reg this_buff_7_ce1;
reg this_buff_7_we1;
reg InImg_data156_read;
reg[15:0] LEF_Img_data157_din;
reg LEF_Img_data157_write;
reg[15:0] SEF_Img_data158_din;
reg SEF_Img_data158_write;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] reg_227;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state11;
wire   [10:0] trunc_ln_fu_233_p4;
reg   [10:0] trunc_ln_reg_384;
wire   [0:0] icmp_ln113_fu_243_p2;
reg   [0:0] icmp_ln113_reg_394;
wire   [2:0] add_ln125_fu_263_p2;
reg   [2:0] add_ln125_reg_404;
wire    ap_CS_fsm_state2;
wire   [13:0] sub_ln176_fu_306_p2;
reg   [13:0] sub_ln176_reg_436;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln131_fu_291_p2;
wire   [2:0] empty_38_fu_312_p1;
reg   [2:0] empty_38_reg_441;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln162_fu_317_p2;
reg   [0:0] icmp_ln162_reg_446;
wire    ap_CS_fsm_state8;
wire   [31:0] add_ln165_fu_323_p2;
reg   [31:0] add_ln165_reg_451;
wire   [11:0] row_3_fu_329_p2;
reg   [11:0] row_3_reg_456;
wire   [0:0] icmp_ln167_fu_340_p2;
reg   [0:0] icmp_ln167_reg_461;
wire   [31:0] add_ln170_fu_346_p2;
reg   [31:0] add_ln170_reg_466;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_start;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_done;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_idle;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_ready;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_InImg_data156_read;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_0_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_0_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_0_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_0_d1;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_1_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_1_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_1_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_1_d1;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_2_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_2_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_2_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_2_d1;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_3_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_3_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_3_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_3_d1;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_4_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_4_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_4_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_4_d1;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_5_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_5_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_5_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_5_d1;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_6_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_6_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_6_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_6_d1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_start;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_done;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_idle;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_ready;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_InImg_data156_read;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_0_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_0_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_0_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_0_d1;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_1_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_1_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_1_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_1_d1;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_2_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_2_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_2_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_2_d1;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_3_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_3_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_3_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_3_d1;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_4_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_4_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_4_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_4_d1;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_5_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_5_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_5_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_5_d1;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_6_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_6_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_6_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_6_d1;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_7_address1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_7_ce1;
wire    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_7_we1;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_7_d1;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_start;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_done;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_idle;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_ready;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_LEF_Img_data157_din;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_LEF_Img_data157_write;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_InImg_data156_read;
wire   [15:0] grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_SEF_Img_data158_din;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_SEF_Img_data158_write;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_0_address0;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_0_ce0;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_1_address0;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_1_ce0;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_2_address0;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_2_ce0;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_3_address0;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_3_ce0;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_4_address0;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_4_ce0;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_5_address0;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_5_ce0;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_6_address0;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_6_ce0;
wire   [10:0] grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_7_address0;
wire    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_7_ce0;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_start;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_done;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_idle;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_ready;
wire   [15:0] grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_LEF_Img_data157_din;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_LEF_Img_data157_write;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_InImg_data156_read;
wire   [15:0] grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_SEF_Img_data158_din;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_SEF_Img_data158_write;
wire   [10:0] grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_0_address0;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_0_ce0;
wire   [10:0] grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_1_address0;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_1_ce0;
wire   [10:0] grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_2_address0;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_2_ce0;
wire   [10:0] grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_3_address0;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_3_ce0;
wire   [10:0] grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_4_address0;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_4_ce0;
wire   [10:0] grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_5_address0;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_5_ce0;
wire   [10:0] grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_6_address0;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_6_ce0;
wire   [10:0] grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_7_address0;
wire    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_7_ce0;
reg    grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_start_reg;
wire    ap_CS_fsm_state12;
reg   [2:0] indvars_iv82_fu_88;
reg    ap_block_state4_on_subcall_done;
reg   [11:0] row_fu_92;
wire   [0:0] icmp_ln112_fu_257_p2;
reg   [31:0] empty_fu_96;
wire   [31:0] select_ln162_fu_334_p3;
reg   [31:0] empty_35_fu_100;
wire   [31:0] select_ln167_fu_361_p3;
wire   [13:0] p_shl_fu_299_p3;
wire   [13:0] zext_ln176_fu_296_p1;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_start_reg = 1'b0;
#0 grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_start_reg = 1'b0;
#0 grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_start_reg = 1'b0;
#0 grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_start_reg = 1'b0;
end

hud_accel_extract_Pipeline_VITIS_LOOP_113_1 grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_start),
    .ap_done(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_done),
    .ap_idle(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_idle),
    .ap_ready(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_ready),
    .InImg_data156_dout(InImg_data156_dout),
    .InImg_data156_num_data_valid(3'd0),
    .InImg_data156_fifo_cap(3'd0),
    .InImg_data156_empty_n(InImg_data156_empty_n),
    .InImg_data156_read(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_InImg_data156_read),
    .trunc_ln(trunc_ln_reg_384),
    .this_buff_0_address1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_0_address1),
    .this_buff_0_ce1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_0_ce1),
    .this_buff_0_we1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_0_we1),
    .this_buff_0_d1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_0_d1),
    .this_buff_1_address1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_1_address1),
    .this_buff_1_ce1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_1_ce1),
    .this_buff_1_we1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_1_we1),
    .this_buff_1_d1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_1_d1),
    .this_buff_2_address1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_2_address1),
    .this_buff_2_ce1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_2_ce1),
    .this_buff_2_we1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_2_we1),
    .this_buff_2_d1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_2_d1),
    .this_buff_3_address1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_3_address1),
    .this_buff_3_ce1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_3_ce1),
    .this_buff_3_we1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_3_we1),
    .this_buff_3_d1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_3_d1),
    .this_buff_4_address1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_4_address1),
    .this_buff_4_ce1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_4_ce1),
    .this_buff_4_we1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_4_we1),
    .this_buff_4_d1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_4_d1),
    .this_buff_5_address1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_5_address1),
    .this_buff_5_ce1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_5_ce1),
    .this_buff_5_we1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_5_we1),
    .this_buff_5_d1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_5_d1),
    .this_buff_6_address1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_6_address1),
    .this_buff_6_ce1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_6_ce1),
    .this_buff_6_we1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_6_we1),
    .this_buff_6_d1(grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_6_d1),
    .indvars_iv82(indvars_iv82_fu_88)
);

hud_accel_extract_Pipeline_VITIS_LOOP_133_2 grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_start),
    .ap_done(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_done),
    .ap_idle(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_idle),
    .ap_ready(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_ready),
    .InImg_data156_dout(InImg_data156_dout),
    .InImg_data156_num_data_valid(3'd0),
    .InImg_data156_fifo_cap(3'd0),
    .InImg_data156_empty_n(InImg_data156_empty_n),
    .InImg_data156_read(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_InImg_data156_read),
    .trunc_ln(trunc_ln_reg_384),
    .this_buff_0_address1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_0_address1),
    .this_buff_0_ce1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_0_ce1),
    .this_buff_0_we1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_0_we1),
    .this_buff_0_d1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_0_d1),
    .this_buff_1_address1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_1_address1),
    .this_buff_1_ce1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_1_ce1),
    .this_buff_1_we1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_1_we1),
    .this_buff_1_d1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_1_d1),
    .this_buff_2_address1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_2_address1),
    .this_buff_2_ce1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_2_ce1),
    .this_buff_2_we1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_2_we1),
    .this_buff_2_d1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_2_d1),
    .this_buff_3_address1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_3_address1),
    .this_buff_3_ce1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_3_ce1),
    .this_buff_3_we1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_3_we1),
    .this_buff_3_d1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_3_d1),
    .this_buff_4_address1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_4_address1),
    .this_buff_4_ce1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_4_ce1),
    .this_buff_4_we1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_4_we1),
    .this_buff_4_d1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_4_d1),
    .this_buff_5_address1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_5_address1),
    .this_buff_5_ce1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_5_ce1),
    .this_buff_5_we1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_5_we1),
    .this_buff_5_d1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_5_d1),
    .this_buff_6_address1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_6_address1),
    .this_buff_6_ce1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_6_ce1),
    .this_buff_6_we1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_6_we1),
    .this_buff_6_d1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_6_d1),
    .this_buff_7_address1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_7_address1),
    .this_buff_7_ce1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_7_ce1),
    .this_buff_7_we1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_7_we1),
    .this_buff_7_d1(grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_7_d1),
    .p_cast(empty_38_reg_441)
);

hud_accel_extract_Pipeline_VITIS_LOOP_145_3 grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_start),
    .ap_done(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_done),
    .ap_idle(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_idle),
    .ap_ready(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_ready),
    .LEF_Img_data157_din(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_LEF_Img_data157_din),
    .LEF_Img_data157_num_data_valid(3'd0),
    .LEF_Img_data157_fifo_cap(3'd0),
    .LEF_Img_data157_full_n(LEF_Img_data157_full_n),
    .LEF_Img_data157_write(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_LEF_Img_data157_write),
    .InImg_data156_dout(InImg_data156_dout),
    .InImg_data156_num_data_valid(3'd0),
    .InImg_data156_fifo_cap(3'd0),
    .InImg_data156_empty_n(InImg_data156_empty_n),
    .InImg_data156_read(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_InImg_data156_read),
    .SEF_Img_data158_din(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_SEF_Img_data158_din),
    .SEF_Img_data158_num_data_valid(3'd0),
    .SEF_Img_data158_fifo_cap(3'd0),
    .SEF_Img_data158_full_n(SEF_Img_data158_full_n),
    .SEF_Img_data158_write(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_SEF_Img_data158_write),
    .trunc_ln(trunc_ln_reg_384),
    .this_buff_0_address0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_0_address0),
    .this_buff_0_ce0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_0_ce0),
    .this_buff_0_q0(this_buff_0_q0),
    .this_buff_1_address0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_1_address0),
    .this_buff_1_ce0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_1_ce0),
    .this_buff_1_q0(this_buff_1_q0),
    .this_buff_2_address0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_2_address0),
    .this_buff_2_ce0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_2_ce0),
    .this_buff_2_q0(this_buff_2_q0),
    .this_buff_3_address0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_3_address0),
    .this_buff_3_ce0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_3_ce0),
    .this_buff_3_q0(this_buff_3_q0),
    .this_buff_4_address0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_4_address0),
    .this_buff_4_ce0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_4_ce0),
    .this_buff_4_q0(this_buff_4_q0),
    .this_buff_5_address0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_5_address0),
    .this_buff_5_ce0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_5_ce0),
    .this_buff_5_q0(this_buff_5_q0),
    .this_buff_6_address0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_6_address0),
    .this_buff_6_ce0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_6_ce0),
    .this_buff_6_q0(this_buff_6_q0),
    .this_buff_7_address0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_7_address0),
    .this_buff_7_ce0(grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_7_ce0),
    .this_buff_7_q0(this_buff_7_q0),
    .empty(reg_227)
);

hud_accel_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4 grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_start),
    .ap_done(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_done),
    .ap_idle(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_idle),
    .ap_ready(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_ready),
    .LEF_Img_data157_din(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_LEF_Img_data157_din),
    .LEF_Img_data157_num_data_valid(3'd0),
    .LEF_Img_data157_fifo_cap(3'd0),
    .LEF_Img_data157_full_n(LEF_Img_data157_full_n),
    .LEF_Img_data157_write(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_LEF_Img_data157_write),
    .InImg_data156_dout(InImg_data156_dout),
    .InImg_data156_num_data_valid(3'd0),
    .InImg_data156_fifo_cap(3'd0),
    .InImg_data156_empty_n(InImg_data156_empty_n),
    .InImg_data156_read(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_InImg_data156_read),
    .SEF_Img_data158_din(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_SEF_Img_data158_din),
    .SEF_Img_data158_num_data_valid(3'd0),
    .SEF_Img_data158_fifo_cap(3'd0),
    .SEF_Img_data158_full_n(SEF_Img_data158_full_n),
    .SEF_Img_data158_write(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_SEF_Img_data158_write),
    .empty(reg_227),
    .sub_ln176(sub_ln176_reg_436),
    .this_buff_0_address0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_0_address0),
    .this_buff_0_ce0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_0_ce0),
    .this_buff_0_q0(this_buff_0_q0),
    .this_buff_1_address0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_1_address0),
    .this_buff_1_ce0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_1_ce0),
    .this_buff_1_q0(this_buff_1_q0),
    .this_buff_2_address0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_2_address0),
    .this_buff_2_ce0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_2_ce0),
    .this_buff_2_q0(this_buff_2_q0),
    .this_buff_3_address0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_3_address0),
    .this_buff_3_ce0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_3_ce0),
    .this_buff_3_q0(this_buff_3_q0),
    .this_buff_4_address0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_4_address0),
    .this_buff_4_ce0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_4_ce0),
    .this_buff_4_q0(this_buff_4_q0),
    .this_buff_5_address0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_5_address0),
    .this_buff_5_ce0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_5_ce0),
    .this_buff_5_q0(this_buff_5_q0),
    .this_buff_6_address0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_6_address0),
    .this_buff_6_ce0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_6_ce0),
    .this_buff_6_q0(this_buff_6_q0),
    .this_buff_7_address0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_7_address0),
    .this_buff_7_ce0(grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_7_ce0),
    .this_buff_7_q0(this_buff_7_q0),
    .trunc_ln(trunc_ln_reg_384)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_start_reg <= 1'b1;
        end else if ((grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_ready == 1'b1)) begin
            grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_start_reg <= 1'b1;
        end else if ((grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_ready == 1'b1)) begin
            grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_start_reg <= 1'b1;
        end else if ((grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_ready == 1'b1)) begin
            grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_start_reg <= 1'b1;
        end else if ((grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_ready == 1'b1)) begin
            grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln112_fu_257_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_35_fu_100 <= 32'd0;
    end else if (((grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        empty_35_fu_100 <= select_ln167_fu_361_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln112_fu_257_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        empty_fu_96 <= 32'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        empty_fu_96 <= select_ln162_fu_334_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvars_iv82_fu_88 <= 3'd0;
    end else if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        indvars_iv82_fu_88 <= add_ln125_reg_404;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln112_fu_257_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        row_fu_92 <= 12'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        row_fu_92 <= row_3_reg_456;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln125_reg_404 <= add_ln125_fu_263_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln165_reg_451 <= add_ln165_fu_323_p2;
        icmp_ln162_reg_446 <= icmp_ln162_fu_317_p2;
        row_3_reg_456 <= row_3_fu_329_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln170_reg_466 <= add_ln170_fu_346_p2;
        icmp_ln167_reg_461 <= icmp_ln167_fu_340_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        empty_38_reg_441 <= empty_38_fu_312_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln113_reg_394 <= icmp_ln113_fu_243_p2;
        trunc_ln_reg_384 <= {{p_read5[11:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state9))) begin
        reg_227 <= empty_35_fu_100;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln131_fu_291_p2 == 1'd0))) begin
        sub_ln176_reg_436 <= sub_ln176_fu_306_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        InImg_data156_read = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_InImg_data156_read;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        InImg_data156_read = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_InImg_data156_read;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        InImg_data156_read = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_InImg_data156_read;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        InImg_data156_read = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_InImg_data156_read;
    end else begin
        InImg_data156_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        LEF_Img_data157_din = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_LEF_Img_data157_din;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        LEF_Img_data157_din = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_LEF_Img_data157_din;
    end else begin
        LEF_Img_data157_din = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_LEF_Img_data157_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        LEF_Img_data157_write = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_LEF_Img_data157_write;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        LEF_Img_data157_write = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_LEF_Img_data157_write;
    end else begin
        LEF_Img_data157_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        SEF_Img_data158_din = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_SEF_Img_data158_din;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        SEF_Img_data158_din = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_SEF_Img_data158_din;
    end else begin
        SEF_Img_data158_din = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_SEF_Img_data158_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        SEF_Img_data158_write = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_SEF_Img_data158_write;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        SEF_Img_data158_write = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_SEF_Img_data158_write;
    end else begin
        SEF_Img_data158_write = 1'b0;
    end
end

always @ (*) begin
    if ((grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_0_address0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_0_address0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_0_address0;
    end else begin
        this_buff_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_0_address1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_0_address1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_0_address1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_0_address1;
    end else begin
        this_buff_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_0_ce0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_0_ce0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_0_ce0;
    end else begin
        this_buff_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_0_ce1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_0_ce1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_0_ce1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_0_ce1;
    end else begin
        this_buff_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_0_d1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_0_d1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_0_d1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_0_d1;
    end else begin
        this_buff_0_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_0_we1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_0_we1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_0_we1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_0_we1;
    end else begin
        this_buff_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_1_address0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_1_address0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_1_address0;
    end else begin
        this_buff_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_1_address1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_1_address1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_1_address1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_1_address1;
    end else begin
        this_buff_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_1_ce0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_1_ce0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_1_ce0;
    end else begin
        this_buff_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_1_ce1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_1_ce1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_1_ce1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_1_ce1;
    end else begin
        this_buff_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_1_d1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_1_d1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_1_d1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_1_d1;
    end else begin
        this_buff_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_1_we1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_1_we1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_1_we1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_1_we1;
    end else begin
        this_buff_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_2_address0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_2_address0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_2_address0;
    end else begin
        this_buff_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_2_address1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_2_address1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_2_address1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_2_address1;
    end else begin
        this_buff_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_2_ce0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_2_ce0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_2_ce0;
    end else begin
        this_buff_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_2_ce1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_2_ce1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_2_ce1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_2_ce1;
    end else begin
        this_buff_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_2_d1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_2_d1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_2_d1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_2_d1;
    end else begin
        this_buff_2_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_2_we1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_2_we1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_2_we1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_2_we1;
    end else begin
        this_buff_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_3_address0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_3_address0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_3_address0;
    end else begin
        this_buff_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_3_address1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_3_address1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_3_address1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_3_address1;
    end else begin
        this_buff_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_3_ce0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_3_ce0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_3_ce0;
    end else begin
        this_buff_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_3_ce1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_3_ce1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_3_ce1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_3_ce1;
    end else begin
        this_buff_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_3_d1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_3_d1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_3_d1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_3_d1;
    end else begin
        this_buff_3_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_3_we1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_3_we1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_3_we1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_3_we1;
    end else begin
        this_buff_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_4_address0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_4_address0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_4_address0;
    end else begin
        this_buff_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_4_address1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_4_address1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_4_address1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_4_address1;
    end else begin
        this_buff_4_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_4_ce0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_4_ce0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_4_ce0;
    end else begin
        this_buff_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_4_ce1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_4_ce1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_4_ce1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_4_ce1;
    end else begin
        this_buff_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_4_d1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_4_d1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_4_d1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_4_d1;
    end else begin
        this_buff_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_4_we1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_4_we1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_4_we1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_4_we1;
    end else begin
        this_buff_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_5_address0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_5_address0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_5_address0;
    end else begin
        this_buff_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_5_address1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_5_address1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_5_address1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_5_address1;
    end else begin
        this_buff_5_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_5_ce0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_5_ce0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_5_ce0;
    end else begin
        this_buff_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_5_ce1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_5_ce1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_5_ce1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_5_ce1;
    end else begin
        this_buff_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_5_d1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_5_d1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_5_d1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_5_d1;
    end else begin
        this_buff_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_5_we1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_5_we1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_5_we1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_5_we1;
    end else begin
        this_buff_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_6_address0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_6_address0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_6_address0;
    end else begin
        this_buff_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_6_address1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_6_address1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_6_address1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_6_address1;
    end else begin
        this_buff_6_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_6_ce0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_6_ce0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_6_ce0;
    end else begin
        this_buff_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_6_ce1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_6_ce1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_6_ce1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_6_ce1;
    end else begin
        this_buff_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_6_d1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_6_d1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_6_d1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_6_d1;
    end else begin
        this_buff_6_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_6_we1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_6_we1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln113_reg_394 == 1'd1))) begin
        this_buff_6_we1 = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_this_buff_6_we1;
    end else begin
        this_buff_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_7_address0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_7_address0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_7_address0;
    end else begin
        this_buff_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        this_buff_7_ce0 = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_this_buff_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        this_buff_7_ce0 = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_this_buff_7_ce0;
    end else begin
        this_buff_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_7_ce1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_7_ce1;
    end else begin
        this_buff_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        this_buff_7_we1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_7_we1;
    end else begin
        this_buff_7_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln112_fu_257_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((icmp_ln112_fu_257_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln113_reg_394 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln131_fu_291_p2 == 1'd1) & (icmp_ln113_reg_394 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln131_fu_291_p2 == 1'd1) & (icmp_ln113_reg_394 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln125_fu_263_p2 = (indvars_iv82_fu_88 + 3'd1);

assign add_ln165_fu_323_p2 = (empty_fu_96 + 32'd1);

assign add_ln170_fu_346_p2 = (empty_35_fu_100 + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_done == 1'b0) & (icmp_ln113_reg_394 == 1'd1));
end

assign empty_38_fu_312_p1 = empty_fu_96[2:0];

assign grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_start = grp_extract_Pipeline_LAST_LINES_VITIS_LOOP_177_4_fu_190_ap_start_reg;

assign grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_start = grp_extract_Pipeline_VITIS_LOOP_113_1_fu_116_ap_start_reg;

assign grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_start = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_ap_start_reg;

assign grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_start = grp_extract_Pipeline_VITIS_LOOP_145_3_fu_162_ap_start_reg;

assign icmp_ln112_fu_257_p2 = ((indvars_iv82_fu_88 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln113_fu_243_p2 = ((trunc_ln_fu_233_p4 != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln131_fu_291_p2 = ((row_fu_92 < p_read14) ? 1'b1 : 1'b0);

assign icmp_ln162_fu_317_p2 = ((empty_fu_96 == 32'd7) ? 1'b1 : 1'b0);

assign icmp_ln167_fu_340_p2 = ((empty_35_fu_100 == 32'd7) ? 1'b1 : 1'b0);

assign p_shl_fu_299_p3 = {{trunc_ln_reg_384}, {3'd0}};

assign row_3_fu_329_p2 = (row_fu_92 + 12'd1);

assign select_ln162_fu_334_p3 = ((icmp_ln162_reg_446[0:0] == 1'b1) ? 32'd0 : add_ln165_reg_451);

assign select_ln167_fu_361_p3 = ((icmp_ln167_reg_461[0:0] == 1'b1) ? 32'd0 : add_ln170_reg_466);

assign sub_ln176_fu_306_p2 = (p_shl_fu_299_p3 - zext_ln176_fu_296_p1);

assign this_buff_7_address1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_7_address1;

assign this_buff_7_d1 = grp_extract_Pipeline_VITIS_LOOP_133_2_fu_138_this_buff_7_d1;

assign trunc_ln_fu_233_p4 = {{p_read5[11:1]}};

assign zext_ln176_fu_296_p1 = trunc_ln_reg_384;

endmodule //hud_accel_extract
