// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hud_accel_GRAYMat2AXIvideo_0_2160_3840_2_3_Pipeline_loop_col_mat2axi (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        LEF_Img_data157_dout,
        LEF_Img_data157_num_data_valid,
        LEF_Img_data157_fifo_cap,
        LEF_Img_data157_empty_n,
        LEF_Img_data157_read,
        lef_ptr_TREADY,
        sof,
        cols,
        sub,
        lef_ptr_TDATA,
        lef_ptr_TVALID,
        lef_ptr_TKEEP,
        lef_ptr_TSTRB,
        lef_ptr_TUSER,
        lef_ptr_TLAST,
        lef_ptr_TID,
        lef_ptr_TDEST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] LEF_Img_data157_dout;
input  [2:0] LEF_Img_data157_num_data_valid;
input  [2:0] LEF_Img_data157_fifo_cap;
input   LEF_Img_data157_empty_n;
output   LEF_Img_data157_read;
input   lef_ptr_TREADY;
input  [0:0] sof;
input  [10:0] cols;
input  [11:0] sub;
output  [15:0] lef_ptr_TDATA;
output   lef_ptr_TVALID;
output  [1:0] lef_ptr_TKEEP;
output  [1:0] lef_ptr_TSTRB;
output  [0:0] lef_ptr_TUSER;
output  [0:0] lef_ptr_TLAST;
output  [0:0] lef_ptr_TID;
output  [0:0] lef_ptr_TDEST;

reg ap_idle;
reg LEF_Img_data157_read;
reg lef_ptr_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln126_reg_189;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln126_fu_154_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    LEF_Img_data157_blk_n;
wire    ap_block_pp0_stage0;
reg    lef_ptr_TDATA_blk_n;
reg   [0:0] sof_2_reg_130;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] axi_last_V_fu_166_p2;
reg   [0:0] axi_last_V_reg_193;
wire    ap_loop_init;
reg   [10:0] j_fu_72;
wire   [10:0] j_2_fu_160_p2;
reg   [10:0] ap_sig_allocacmp_j_1;
reg    ap_block_pp0_stage0_01001;
wire   [11:0] zext_ln126_fu_150_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_180;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

hud_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln126_fu_154_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_72 <= j_2_fu_160_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_72 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            sof_2_reg_130 <= sof;
        end else if ((1'b1 == ap_condition_180)) begin
            sof_2_reg_130 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln126_fu_154_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        axi_last_V_reg_193 <= axi_last_V_fu_166_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln126_reg_189 <= icmp_ln126_fu_154_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln126_reg_189 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        LEF_Img_data157_blk_n = LEF_Img_data157_empty_n;
    end else begin
        LEF_Img_data157_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln126_reg_189 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        LEF_Img_data157_read = 1'b1;
    end else begin
        LEF_Img_data157_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln126_fu_154_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln126_reg_189 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lef_ptr_TDATA_blk_n = lef_ptr_TREADY;
    end else begin
        lef_ptr_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln126_reg_189 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lef_ptr_TVALID = 1'b1;
    end else begin
        lef_ptr_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((lef_ptr_TREADY == 1'b0) & (icmp_ln126_reg_189 == 1'd0)) | ((icmp_ln126_reg_189 == 1'd0) & (1'b0 == LEF_Img_data157_empty_n))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((lef_ptr_TREADY == 1'b0) & (icmp_ln126_reg_189 == 1'd0)) | ((icmp_ln126_reg_189 == 1'd0) & (1'b0 == LEF_Img_data157_empty_n))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state2_io) | ((lef_ptr_TREADY == 1'b0) & (icmp_ln126_reg_189 == 1'd0)) | ((icmp_ln126_reg_189 == 1'd0) & (1'b0 == LEF_Img_data157_empty_n))));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_io = ((lef_ptr_TREADY == 1'b0) & (icmp_ln126_reg_189 == 1'd0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((lef_ptr_TREADY == 1'b0) & (icmp_ln126_reg_189 == 1'd0)) | ((icmp_ln126_reg_189 == 1'd0) & (1'b0 == LEF_Img_data157_empty_n)));
end

always @ (*) begin
    ap_condition_180 = ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln126_reg_189 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign axi_last_V_fu_166_p2 = ((zext_ln126_fu_150_p1 == sub) ? 1'b1 : 1'b0);

assign icmp_ln126_fu_154_p2 = ((ap_sig_allocacmp_j_1 == cols) ? 1'b1 : 1'b0);

assign j_2_fu_160_p2 = (ap_sig_allocacmp_j_1 + 11'd1);

assign lef_ptr_TDATA = LEF_Img_data157_dout;

assign lef_ptr_TDEST = 1'd0;

assign lef_ptr_TID = 1'd0;

assign lef_ptr_TKEEP = 2'd3;

assign lef_ptr_TLAST = axi_last_V_reg_193;

assign lef_ptr_TSTRB = 2'd0;

assign lef_ptr_TUSER = sof_2_reg_130;

assign zext_ln126_fu_150_p1 = ap_sig_allocacmp_j_1;

endmodule //hud_accel_GRAYMat2AXIvideo_0_2160_3840_2_3_Pipeline_loop_col_mat2axi
