set XPART xc7z045-ffg900-2
set CSIM 1
set CSYNTH 1
set COSIM 0
set VIVADO_SYN 0
set VIVADO_IMPL 0
set XF_PROJ_ROOT "/home/trevor/repo/Vitis_Libraries/vision"
set OPENCV_INCLUDE "/usr/local/include/opencv4"
set OPENCV_LIB "/usr/local/lib"
set CUR_DIR "/home/trevor/Documents/xilinx/basys3_pong2/vitis/hud3"
