-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_tpg_0_0_tpgPatternCheckerBoard is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    y : IN STD_LOGIC_VECTOR (15 downto 0);
    x : IN STD_LOGIC_VECTOR (15 downto 0);
    width : IN STD_LOGIC_VECTOR (13 downto 0);
    height : IN STD_LOGIC_VECTOR (13 downto 0);
    color : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of design_1_v_tpg_0_0_tpgPatternCheckerBoard is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_0_2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv14_F : STD_LOGIC_VECTOR (13 downto 0) := "00000000001111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal yCount_V_3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal hBarSel_3 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal xCount_V_3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal tpgCheckerBoardArray_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal tpgCheckerBoardArray_ce0 : STD_LOGIC;
    signal tpgCheckerBoardArray_q0 : STD_LOGIC_VECTOR (1 downto 0);
    signal tpgBarSelRgb_r15_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal tpgBarSelRgb_r15_ce0 : STD_LOGIC;
    signal tpgBarSelRgb_r15_q0 : STD_LOGIC_VECTOR (1 downto 0);
    signal tpgBarSelRgb_g13_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal tpgBarSelRgb_g13_ce0 : STD_LOGIC;
    signal tpgBarSelRgb_g13_q0 : STD_LOGIC_VECTOR (1 downto 0);
    signal tpgBarSelRgb_b11_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal tpgBarSelRgb_b11_ce0 : STD_LOGIC;
    signal tpgBarSelRgb_b11_q0 : STD_LOGIC_VECTOR (1 downto 0);
    signal tpgBarSelYuv_y21_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal tpgBarSelYuv_y21_ce0 : STD_LOGIC;
    signal tpgBarSelYuv_y21_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal tpgBarSelYuv_v19_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal tpgBarSelYuv_v19_ce0 : STD_LOGIC;
    signal tpgBarSelYuv_v19_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal tpgBarSelYuv_u17_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal tpgBarSelYuv_u17_ce0 : STD_LOGIC;
    signal tpgBarSelYuv_u17_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal cmp61_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal and_ln1560_1_fu_473_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1560_1_reg_575 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1560_1_reg_575_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_vBarSel_2_loc_2_phi_fu_198_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_vBarSel_2_loc_2_reg_195 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1518_1_fu_265_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1073_fu_275_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1523_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1530_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1518_fu_253_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_hBarSel_3_loc_1_phi_fu_212_p6 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_hBarSel_3_loc_1_reg_209 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln1073_3_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1548_fu_409_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln1555_fu_456_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln1555_1_fu_483_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln1530_fu_327_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln886_fu_346_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln887_fu_397_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln886_4_fu_422_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln1510_fu_225_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln5_fu_231_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln1518_fu_259_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1511_fu_247_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_285_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1542_fu_295_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1073_fu_305_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ret_V_fu_299_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln1073_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal barWidthMinSamples_fu_241_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tBarSel_fu_446_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln1506_fu_221_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_461_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1560_fu_467_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp84_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln1555_fu_479_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln259_fu_497_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp_fu_505_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tpgBarSelRgb_r_load_cast_fu_493_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tpgBarSelRgb_b_load_cast_fu_501_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_val_V_fu_519_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_val_V_9_fu_512_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_val_V_10_fu_526_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_156 : BOOLEAN;
    signal ap_condition_171 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_tpg_0_0_tpgPatternCheckerBoard_tpgCheckerBoardArray_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_r_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_g_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_b_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component design_1_v_tpg_0_0_tpgPatternCheckerBoard_tpgBarSelYuv_y21_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component design_1_v_tpg_0_0_tpgPatternCheckerBoard_tpgBarSelYuv_v19_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component design_1_v_tpg_0_0_tpgPatternCheckerBoard_tpgBarSelYuv_u17_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    tpgCheckerBoardArray_U : component design_1_v_tpg_0_0_tpgPatternCheckerBoard_tpgCheckerBoardArray_ROM_AUTO_1R
    generic map (
        DataWidth => 2,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tpgCheckerBoardArray_address0,
        ce0 => tpgCheckerBoardArray_ce0,
        q0 => tpgCheckerBoardArray_q0);

    tpgBarSelRgb_r15_U : component design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_r_ROM_AUTO_1R
    generic map (
        DataWidth => 2,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tpgBarSelRgb_r15_address0,
        ce0 => tpgBarSelRgb_r15_ce0,
        q0 => tpgBarSelRgb_r15_q0);

    tpgBarSelRgb_g13_U : component design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_g_ROM_AUTO_1R
    generic map (
        DataWidth => 2,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tpgBarSelRgb_g13_address0,
        ce0 => tpgBarSelRgb_g13_ce0,
        q0 => tpgBarSelRgb_g13_q0);

    tpgBarSelRgb_b11_U : component design_1_v_tpg_0_0_tpgPatternDPColorSquare_DPtpgBarSelRgb_VESA_b_ROM_AUTO_1R
    generic map (
        DataWidth => 2,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tpgBarSelRgb_b11_address0,
        ce0 => tpgBarSelRgb_b11_ce0,
        q0 => tpgBarSelRgb_b11_q0);

    tpgBarSelYuv_y21_U : component design_1_v_tpg_0_0_tpgPatternCheckerBoard_tpgBarSelYuv_y21_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tpgBarSelYuv_y21_address0,
        ce0 => tpgBarSelYuv_y21_ce0,
        q0 => tpgBarSelYuv_y21_q0);

    tpgBarSelYuv_v19_U : component design_1_v_tpg_0_0_tpgPatternCheckerBoard_tpgBarSelYuv_v19_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tpgBarSelYuv_v19_address0,
        ce0 => tpgBarSelYuv_v19_ce0,
        q0 => tpgBarSelYuv_v19_q0);

    tpgBarSelYuv_u17_U : component design_1_v_tpg_0_0_tpgPatternCheckerBoard_tpgBarSelYuv_u17_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tpgBarSelYuv_u17_address0,
        ce0 => tpgBarSelYuv_u17_ce0,
        q0 => tpgBarSelYuv_u17_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    hBarSel_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_156)) then
                if ((icmp_ln1518_fu_253_p2 = ap_const_lv1_1)) then 
                    hBarSel_3 <= ap_const_lv3_0;
                elsif (((icmp_ln1073_3_fu_391_p2 = ap_const_lv1_0) and (icmp_ln1518_fu_253_p2 = ap_const_lv1_0))) then 
                    hBarSel_3 <= add_ln1548_fu_409_p2;
                end if;
            end if; 
        end if;
    end process;

    vBarSel_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_156)) then
                if ((icmp_ln1518_1_fu_265_p2 = ap_const_lv1_1)) then 
                    vBarSel_2 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_condition_171)) then 
                    vBarSel_2 <= add_ln1530_fu_327_p2;
                end if;
            end if; 
        end if;
    end process;

    xCount_V_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_156)) then
                if ((icmp_ln1518_fu_253_p2 = ap_const_lv1_1)) then 
                    xCount_V_3 <= ap_const_lv10_0;
                elsif (((icmp_ln1073_3_fu_391_p2 = ap_const_lv1_1) and (icmp_ln1518_fu_253_p2 = ap_const_lv1_0))) then 
                    xCount_V_3 <= add_ln886_4_fu_422_p2;
                elsif (((icmp_ln1073_3_fu_391_p2 = ap_const_lv1_0) and (icmp_ln1518_fu_253_p2 = ap_const_lv1_0))) then 
                    xCount_V_3 <= sub_ln887_fu_397_p2;
                end if;
            end if; 
        end if;
    end process;

    yCount_V_3_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_156)) then
                if ((icmp_ln1518_1_fu_265_p2 = ap_const_lv1_1)) then 
                    yCount_V_3 <= ap_const_lv10_0_2;
                elsif (((icmp_ln1518_1_fu_265_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln1523_fu_315_p2))) then 
                    yCount_V_3 <= add_ln886_fu_346_p2;
                elsif ((ap_const_boolean_1 = ap_condition_171)) then 
                    yCount_V_3 <= ap_const_lv10_0_1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln1560_1_reg_575 <= and_ln1560_1_fu_473_p2;
                and_ln1560_1_reg_575_pp0_iter1_reg <= and_ln1560_1_reg_575;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1510_fu_225_p2 <= std_logic_vector(unsigned(width) + unsigned(ap_const_lv14_F));
    add_ln1511_fu_247_p2 <= std_logic_vector(unsigned(height) + unsigned(ap_const_lv14_F));
    add_ln1530_fu_327_p2 <= std_logic_vector(unsigned(vBarSel_2) + unsigned(ap_const_lv8_1));
    add_ln1548_fu_409_p2 <= std_logic_vector(unsigned(hBarSel_3) + unsigned(ap_const_lv3_1));
    add_ln886_4_fu_422_p2 <= std_logic_vector(unsigned(xCount_V_3) + unsigned(ap_const_lv10_1));
    add_ln886_fu_346_p2 <= std_logic_vector(unsigned(yCount_V_3) + unsigned(ap_const_lv10_1));
    and_ln1523_fu_315_p2 <= (icmp_ln1518_fu_253_p2 and icmp_ln1073_fu_309_p2);
    and_ln1560_1_fu_473_p2 <= (cmp84_fu_376_p2 and and_ln1560_fu_467_p2);
    and_ln1560_fu_467_p2 <= (trunc_ln1506_fu_221_p1 and sel_tmp1_fu_461_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_156_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
                ap_condition_156 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_171_assign_proc : process(icmp_ln1518_1_fu_265_p2, and_ln1523_fu_315_p2, icmp_ln1518_fu_253_p2)
    begin
                ap_condition_171 <= ((icmp_ln1518_fu_253_p2 = ap_const_lv1_1) and (icmp_ln1518_1_fu_265_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln1523_fu_315_p2));
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_hBarSel_3_loc_1_phi_fu_212_p6_assign_proc : process(hBarSel_3, icmp_ln1518_fu_253_p2, ap_phi_reg_pp0_iter0_hBarSel_3_loc_1_reg_209, icmp_ln1073_3_fu_391_p2, add_ln1548_fu_409_p2)
    begin
        if (((icmp_ln1073_3_fu_391_p2 = ap_const_lv1_0) and (icmp_ln1518_fu_253_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_hBarSel_3_loc_1_phi_fu_212_p6 <= add_ln1548_fu_409_p2;
        elsif (((icmp_ln1073_3_fu_391_p2 = ap_const_lv1_1) and (icmp_ln1518_fu_253_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_hBarSel_3_loc_1_phi_fu_212_p6 <= hBarSel_3;
        elsif ((icmp_ln1518_fu_253_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_hBarSel_3_loc_1_phi_fu_212_p6 <= ap_const_lv3_0;
        else 
            ap_phi_mux_hBarSel_3_loc_1_phi_fu_212_p6 <= ap_phi_reg_pp0_iter0_hBarSel_3_loc_1_reg_209;
        end if; 
    end process;


    ap_phi_mux_vBarSel_2_loc_2_phi_fu_198_p8_assign_proc : process(ap_phi_reg_pp0_iter0_vBarSel_2_loc_2_reg_195, icmp_ln1518_1_fu_265_p2, trunc_ln1073_fu_275_p1, and_ln1523_fu_315_p2, xor_ln1530_fu_333_p2, icmp_ln1518_fu_253_p2)
    begin
        if (((icmp_ln1518_fu_253_p2 = ap_const_lv1_1) and (icmp_ln1518_1_fu_265_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln1523_fu_315_p2))) then 
            ap_phi_mux_vBarSel_2_loc_2_phi_fu_198_p8 <= xor_ln1530_fu_333_p2;
        elsif ((((icmp_ln1518_fu_253_p2 = ap_const_lv1_0) and (icmp_ln1518_1_fu_265_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln1523_fu_315_p2)) or ((icmp_ln1518_1_fu_265_p2 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln1523_fu_315_p2)))) then 
            ap_phi_mux_vBarSel_2_loc_2_phi_fu_198_p8 <= trunc_ln1073_fu_275_p1;
        elsif ((icmp_ln1518_1_fu_265_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_vBarSel_2_loc_2_phi_fu_198_p8 <= ap_const_lv1_0;
        else 
            ap_phi_mux_vBarSel_2_loc_2_phi_fu_198_p8 <= ap_phi_reg_pp0_iter0_vBarSel_2_loc_2_reg_195;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_hBarSel_3_loc_1_reg_209 <= "XXX";
    ap_phi_reg_pp0_iter0_vBarSel_2_loc_2_reg_195 <= "X";

    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= pix_val_V_fu_519_p3;
    ap_return_1 <= pix_val_V_9_fu_512_p3;
    ap_return_2 <= pix_val_V_10_fu_526_p3;
    barWidthMinSamples_fu_241_p2 <= std_logic_vector(unsigned(trunc_ln5_fu_231_p4) + unsigned(ap_const_lv10_3FF));
    cmp61_fu_370_p2 <= "1" when (color = ap_const_lv8_0) else "0";
    cmp84_fu_376_p2 <= "0" when (color = ap_const_lv8_1) else "1";
    icmp_ln1073_3_fu_391_p2 <= "1" when (unsigned(xCount_V_3) < unsigned(barWidthMinSamples_fu_241_p2)) else "0";
    icmp_ln1073_fu_309_p2 <= "1" when (signed(zext_ln1073_fu_305_p1) < signed(ret_V_fu_299_p2)) else "0";
    icmp_ln1518_1_fu_265_p2 <= "1" when (or_ln1518_fu_259_p2 = ap_const_lv16_0) else "0";
    icmp_ln1518_fu_253_p2 <= "1" when (x = ap_const_lv16_0) else "0";
    or_ln1518_fu_259_p2 <= (y or x);
    pix_val_V_10_fu_526_p3 <= 
        tpgBarSelRgb_b_load_cast_fu_501_p1 when (cmp61_fu_370_p2(0) = '1') else 
        tpgBarSelYuv_v19_q0;
    pix_val_V_9_fu_512_p3 <= 
        tpgBarSelYuv_v19_q0 when (and_ln1560_1_reg_575_pp0_iter1_reg(0) = '1') else 
        sel_tmp_fu_505_p3;
    pix_val_V_fu_519_p3 <= 
        tpgBarSelRgb_r_load_cast_fu_493_p1 when (cmp61_fu_370_p2(0) = '1') else 
        tpgBarSelYuv_y21_q0;
    ret_V_fu_299_p2 <= std_logic_vector(unsigned(zext_ln1542_fu_295_p1) + unsigned(ap_const_lv11_7FF));
    sel_tmp1_fu_461_p2 <= (cmp61_fu_370_p2 xor ap_const_lv1_1);
    sel_tmp_fu_505_p3 <= 
        sext_ln259_fu_497_p1 when (cmp61_fu_370_p2(0) = '1') else 
        tpgBarSelYuv_u17_q0;
        sext_ln1555_fu_479_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tpgCheckerBoardArray_q0),3));

        sext_ln259_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tpgBarSelRgb_g13_q0),8));

    sub_ln887_fu_397_p2 <= std_logic_vector(unsigned(xCount_V_3) - unsigned(barWidthMinSamples_fu_241_p2));
    tBarSel_fu_446_p4 <= ((ap_phi_mux_vBarSel_2_loc_2_phi_fu_198_p8 & ap_const_lv1_0) & ap_phi_mux_hBarSel_3_loc_1_phi_fu_212_p6);
    tmp_fu_285_p4 <= add_ln1511_fu_247_p2(13 downto 4);
    tpgBarSelRgb_b11_address0 <= zext_ln1555_1_fu_483_p1(3 - 1 downto 0);

    tpgBarSelRgb_b11_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tpgBarSelRgb_b11_ce0 <= ap_const_logic_1;
        else 
            tpgBarSelRgb_b11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

        tpgBarSelRgb_b_load_cast_fu_501_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tpgBarSelRgb_b11_q0),8));

    tpgBarSelRgb_g13_address0 <= zext_ln1555_1_fu_483_p1(3 - 1 downto 0);

    tpgBarSelRgb_g13_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tpgBarSelRgb_g13_ce0 <= ap_const_logic_1;
        else 
            tpgBarSelRgb_g13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tpgBarSelRgb_r15_address0 <= zext_ln1555_1_fu_483_p1(3 - 1 downto 0);

    tpgBarSelRgb_r15_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tpgBarSelRgb_r15_ce0 <= ap_const_logic_1;
        else 
            tpgBarSelRgb_r15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

        tpgBarSelRgb_r_load_cast_fu_493_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tpgBarSelRgb_r15_q0),8));

    tpgBarSelYuv_u17_address0 <= zext_ln1555_1_fu_483_p1(3 - 1 downto 0);

    tpgBarSelYuv_u17_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tpgBarSelYuv_u17_ce0 <= ap_const_logic_1;
        else 
            tpgBarSelYuv_u17_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tpgBarSelYuv_v19_address0 <= zext_ln1555_1_fu_483_p1(3 - 1 downto 0);

    tpgBarSelYuv_v19_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tpgBarSelYuv_v19_ce0 <= ap_const_logic_1;
        else 
            tpgBarSelYuv_v19_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tpgBarSelYuv_y21_address0 <= zext_ln1555_1_fu_483_p1(3 - 1 downto 0);

    tpgBarSelYuv_y21_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tpgBarSelYuv_y21_ce0 <= ap_const_logic_1;
        else 
            tpgBarSelYuv_y21_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tpgCheckerBoardArray_address0 <= zext_ln1555_fu_456_p1(5 - 1 downto 0);

    tpgCheckerBoardArray_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tpgCheckerBoardArray_ce0 <= ap_const_logic_1;
        else 
            tpgCheckerBoardArray_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln1073_fu_275_p1 <= vBarSel_2(1 - 1 downto 0);
    trunc_ln1506_fu_221_p1 <= x(1 - 1 downto 0);
    trunc_ln5_fu_231_p4 <= add_ln1510_fu_225_p2(13 downto 4);
    xor_ln1530_fu_333_p2 <= (trunc_ln1073_fu_275_p1 xor ap_const_lv1_1);
    zext_ln1073_fu_305_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(yCount_V_3),11));
    zext_ln1542_fu_295_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_285_p4),11));
    zext_ln1555_1_fu_483_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1555_fu_479_p1),64));
    zext_ln1555_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tBarSel_fu_446_p4),64));
end behav;
